### PR TITLE
Add branch alias for master

### PR DESCRIPTION
**Pull request by yguedidi**

### CODE REVIEW

**Comment by mnapoli** [comment]
I'm not a big fan of this because it requires manually updating `composer.json` when new releases are made, and additionally it's not compatible with projects that starts with `0.*` versions.

What is the gain from that? It's not a good thing to require things from anything other than tags anyway

**Comment by yguedidi** [comment]
The main gain of this is that it avoid unexpected BC breaks when updating a project that uses this one as a dependancy.
Require `^1.0@dev` is better than require `dev-master`, because if `master` branch of the required project break things, it will break the project (see #14 for an example).

About `0.*` version, they should be tagged, so project will explicitly require the needed version :)

**Comment by mnapoli** [comment]
`1.*` versions should be tagged too so I don't see how `1.0@dev` is different. People should use stable versions, using the branch alias is useful in very specific scenarios but given the downsides and the fact that it's a very specific need I don't think it should be in a project template.

**Comment by yguedidi** [comment]
> People should use stable versions

I know that. :)

When you just start a new project using this project template (which is my case), you may not have tagged any stable version yet because you still develop, but you want some users to early adopt your project, at least for testing.

Telling them to require `^1.0@dev` instead of `dev-master` will protect them from BC breaks when, in the future, you will tag your last `1.x` release and start develop a `2.0` in `master` branch, assuming they forgot to update their `composer.json`

**Comment by mnapoli** [comment]
Oh OK I understand your need now. In that case I encourage you to tag `0.*` versions, that allows to encourage people to require stable versions as well as break BC (between 0.* versions, which is allowed in SemVer). Here is an example: https://github.com/stratifyphp/framework/releases

**Comment by yguedidi** [comment]
OK, as you want, I think I just don't like `0.*` releases because from a composer point of view, they have a stable stability, and I want may project to have a dev stability during the development phase (ie cannot be required without `@dev`).
And I feel using a branch alias is an appropriate compromise.

Closing

**Pull request closed without merging**
